FROM python:3.12.8-slim

WORKDIR /app
COPY requirements-test.txt requirements.txt ./
RUN pip install --no-cache-dir -r requirements-test.txt
COPY . .
CMD ["python", "-m", "unittest", "discover", "-s", "tests", "-v"]
